### ISSUE TITLE
与原版端统一的配方获取方式

### ISSUE THREAD

**Issue by prprnya** [Sinbing/LBS_Ez_Craft_datapack#2]
Rua，在原版服务端中，几乎所有配方都有其对应的基于进度的获取方式（比如获得6个铁锭时右上角提示可合成铁活板门），这种机制的本质是 触发后以对应配方的解锁作为奖励、且不会在进度视图中显示的**进度**，所以希望能够在此数据包中加入与配方对应的进度（也许高考完之后我就有时间来帮忙写了QwQ）

**Comment by Sinbing** [comment]
rue
配方书的数据包我现在其实还不会写（逃
而且最近期末在准备论文了估计不怎么会动
不过游戏内做好配方书的支持肯定还是想的w
有时间一定做（咕咕咕）
